<?php

/**
 * @file
 * Contains entityconnect.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\entityconnect\ConfigurableEntityconnectItem;


/**
 * Implements hook_help().
 */
function entityconnect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entityconnect module.
    case 'help.page.entityconnect':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Entity Connect') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function entityconnect_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_field_info_alter().
 */
function entityconnect_field_info_alter(&$info) {
  var_dump('tata');
  // Make the entity reference field configurable.
  $info['entity_reference']['no_ui'] = FALSE;
//  $info['entity_reference']['class'] = '\Drupal\entity_reference\ConfigurableEntityReferenceItem';
  $info['entity_reference']['class'] = '\Drupal\entityconnect\ConfigurableEntityconnectItem';
  $info['entity_reference']['list_class'] = '\Drupal\Core\Field\EntityReferenceFieldItemList';
  $info['entity_reference']['default_widget'] = 'entity_reference_autocomplete';
  $info['entity_reference']['default_formatter'] = 'entity_reference_label';
  $info['entity_reference']['provider'] = 'entity_reference';

}
